name: Build and Deploy

on: [ push ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Build
      run: python main.py

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: backup
        folder: ./dist

